### ISSUE TITLE
Use coffeescript, ECMAScript 6 or Javascript?

### ISSUE THREAD

**Issue by fespinoza** [hyperoslo/javascript-playbook#1]
basically the question, should we use coffeescript to code the projects, just plain javascript? or try to get the future now with ECMAScript 6, instead of coffee?
- coffeescript is way more fun to code with than plain JS
- plain JS is the most "universal" alternative
- ECMAScript 6 is not yet finished, although there are some tools around to start using it today

**Comment by fespinoza** [comment]
I think @timkurvers will definitively have something to say here

**Comment by timkurvers** [comment]
Seeing as Angular 2.0 will (may?) be moving to TypeScript, that's also an alternative worth considering. I'd definitely pick ES6 over ES5, as it contains a lot of features we would otherwise be using CoffeeScript for.

As for CoffeeScript vs ES6, I'm still on the fence: executable class bodies are missing in ES6 and those curly braces make me sad. Had a quick chat with @sindrenm and I'm not sure whether CoffeeScript will ever support ES6, which may be a risky investment.

**Comment by fespinoza** [comment]
So I guess the way to go right now is to go with Coffescript at least for a while, knowing that we will potentially move to ES6

**Comment by sindrenm** [comment]
TypeScript sounds like the safe way to go here, although it might be difficult in projects that aren't exclusively Angular, like a Rails app that uses Angular on the front-end. However, I would definitely consider ditching CoffeeScript for future projects. From the top of my head, the only big thing CoffeeScript gives you that ES6 doesn't is the lack of curlies and semicolons, and I can definitely live with writing those if it also means I write totally valid script that the browser can understand without any transpiling. Of course, in the beginning one would need to use tools such as [Babel](https://babeljs.io) or [Traceur](https://github.com/google/traceur-compiler), but in the future, that same code would be valid in the browser, which is a big thing in my opinion.

**Comment by timkurvers** [comment]
Agreed @sindrenm :+1:

**Comment by mathiasbno** [comment]
I like this! Maybe you would like to present this at the front-end meetup @sindrenm ^^

**Comment by sindrenm** [comment]
Oh shit.

**Comment by mathiasbno** [comment]
Already signed you up :heart:

**Comment by fespinoza** [comment]
so it seems like an agreement here, so TypeScript it is

I personally don't know it... what it's good about it?

**Comment by sindrenm** [comment]
They have a 161 page [documentation](http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.pdf) in PDF you can read. :stuck_out_tongue_closed_eyes:

**Comment by timkurvers** [comment]
Type safety, interfaces and supposedly annotations (soon?). Anything else you can think of @sindrenm?

**Comment by sindrenm** [comment]
That's pretty much it. And some minor things, like it has bears much closer resemblance to the new ES6 standard and is backed by both Google and Microsoft.

**Comment by sindrenm** [comment]
![brown-bear-head](https://cloud.githubusercontent.com/assets/386122/6684327/84e14250-cc90-11e4-89d2-f4182e50ef71.jpg)

**Comment by fespinoza** [comment]
I did not like that typescript was maintained by Microsoft... it's like... microsoft uuggh

**Comment by timkurvers** [comment]
If we were to judge languages, products etc. like that, we might as well go out of business :wink:

**Comment by fespinoza** [comment]
but I want to be hipster! :D

**Comment by sindrenm** [comment]
You're not being a hipster by using Chrome, bro. :wink:

**Comment by mathiasbno** [comment]
![048](https://cloud.githubusercontent.com/assets/5957456/6696348/e94368ce-cce8-11e4-9bcf-493fee97d5a8.jpg)

**Comment by JozoSalt** [comment]
I prefer coffescript, just because its what I have always used :) and I don't like curly brackets and semicolons. But I can´t say much about typescript sense I never used it, but willing to try it out.

**Comment by sindrenm** [comment]
Yeah, I've never really used TypeScript either, just plain JS and CoffeeScript. However, I have my hopes up for it. :smiley:

**Comment by jamiebuilds** [comment]
Hi, Babel contributor here. TypeScript is great if you really like types (Flow is also a great choice), CoffeeScript is great if you hate semicolons or curly braces. However, TypeScript has a lot of spec incompatibilities and coffeescript has to change drastically if it ever is to support anything more than ES3 code.

Babel has tons of new platform features coming in ES6+ which are really useful. Stuff like [Async Functions](http://jakearchibald.com/2014/es7-async-functions/), [Modules](http://babeljs.io/docs/learn-es6/#modules), and [tail recursion optimization](http://jsperf.com/tco/17). Babel is extremely strict about spec compliancy and will set you up on the standards track which will have even cooler stuff in the future. Imagine how powerful JavaScript will be by ES8 or 9! (which are scheduled as yearly releases btw)

If you have any questions feel free to ping me, or join our support chat https://gitter.im/babel/babel

**Comment by jgorset** [comment]
Hi @thejameskyle, and thanks for chiming in! I like the prospect of Babel if the idea is that EcmaScript will suck radically less pretty fast; in a world where EcmaScript is already awesome, there is no need for CoffeeScript or TypeScript.

**Comment by sindrenm** [comment]
For most JS projects, I would prefer using something as close to the standard as possible, or, if the standard is good enough, use the standard. CoffeeScript has some awesome stuff that makes writing good code a lot easier, but a lot of this is [being implemented in ES6](https://robots.thoughtbot.com/replace-coffeescript-with-es6), so I don't really think there's a reason for using CoffeeScript anymore. With Babel in the mix (thanks a lot, @thejameskyle, btw!), we can use ES6 features right away. For vanilla JS projects anyway.

For Angular 2 projects, however, I suggest we move over to TypeScript, since they're building the language with TypeScript 1.5 in mind, using annotations and whatnot. We'll be [lacking some ES6 features](https://github.com/Microsoft/TypeScript/wiki/Roadmap#15) by using TypeScript 1.5, however, but I think we'll manage.

**Comment by jamiebuilds** [comment]
For the record we're working with the Angular team to ensure a great experience with Angular with plain JS/Babel, we were just down at the Google campus last Thursday.

**Comment by sindrenm** [comment]
Ah, that sounds great! Then maybe we won't even need to get started with TypeScript (sorry about that, @fespinoza). :grinning:

**Comment by fespinoza** [comment]
hahhaa Sindre... for me it's ok not to use typescript, I just want to use a modern language and that we all agree on it, there are many alternatives right now

but then again, as conventions refer.. we can choose any, try it for a while and then check if we need to re-think our conventions.
