### ISSUE TITLE
Package repositories

### ISSUE THREAD

**Issue by sindrenm** [hyperoslo/javascript-playbook#13]
There are a ton of JavaScript package repositories out there, the most popular ones being [npm](http://npmjs.org) and [Bower](http://bower.io). There's also [Component](https://github.com/componentjs/component), [webpack](http://webpack.github.io), [jspm](http://jspm.io), [Jam](http://jamjs.org), [Duo](http://duojs.org) and probably a whole lot more. I'm not keen on releasing on all of them, the question is where do we make it available and where do we not?

**Comment by sindrenm** [comment]
Copied over from https://github.com/hyperoslo/hyper-content-for-angular/issues/16 as this actually is a general question which affects every piece of JavaScript we decide to open-source.

**Comment by sindrenm** [comment]
So, npm aims at being **the one** package manager and repository for JavaScript stuff, be it for the server-side, client-side or both. They did read about [npm and front-end packaging](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging), and there are some issues with using it as a front-end package manager, but some of these can be avoided to some extent. There is also another blog post about [using npm on the client side](http://dontkry.com/posts/code/using-npm-on-the-client-side.html), which aims to convince us that npm works perfectly fine with client-side assets.

**Comment by sindrenm** [comment]
When it comes to testing, [Karma](http://karma-runner.github.io) is the de facto test runner out there for JS projects. Since [installing Karma requires npm](http://karma-runner.github.io/0.12/intro/installation.html), we might decide to use npm. I imagine other neat tools also being available only through npm.

**Comment by timkurvers** [comment]
My vote's on npm but I think it might be a good idea to support Bower, too. Not too sure about the other ones, are they used muchly?

Tried to get hold of some stats, too:
- npm: 133,523 packages
- Bower: 29,484 packages

**Comment by sindrenm** [comment]
npm would obviously have more packages than Bower as it's hosting both server-side and client-side packages, whereas Bower focuses on the client-side ones. npm seems a little bit more difficult with front-end packages, but maybe we could solve most of that with Browserify? That would enable us to use `require` form the browser, at least. Not sure if it's necessary, though.

**Comment by timkurvers** [comment]
:+1: for Browserify, have used it on most projects, it's fantastic.

**Comment by sindrenm** [comment]
So we'd release it though npm (and possibly also Bower), and add Browserify as a dependency in package.json?

**Comment by timkurvers** [comment]
You can make it a dev dependency, and build a browser-compatible version using Browserify and stuff it in `dist` (which may be where Bower expects it to be too?)

If somebody wanted to include your package, they could use `require`s and opt to use Browserify or not.

**Comment by sindrenm** [comment]
Oh, that's really nice, @timkurvers! I like that approach. :+1:

**Comment by fespinoza** [comment]
I agree with what you have discussed here... npm for all packages and bower for front-end stuff

**Comment by jgorset** [comment]
Isn't the discussion between @sindrenm and @timkurvers leaning towards npm for everything, though, @fespinoza? :p

**Comment by jgorset** [comment]
Sorry. Reading is hard.

**Comment by jgorset** [comment]
I bet you're going to wonder where all my comments went now.

**Comment by jgorset** [comment]
> npm for all packages and bower for front-end stuff

:+1:

**Comment by timkurvers** [comment]
:dancers:

**Comment by sindrenm** [comment]
Great! Closing this. :+1:

**Comment by timkurvers** [comment]
👍
