### ISSUE TITLE
ES6 no-parameter function syntax

### ISSUE THREAD

**Issue by sindrenm** [hyperoslo/javascript-playbook#15]
Small question that we might resolve fairly quickly, but worth asking, I guess:

I've come across multiple ways of writing ES6 arrow functions with empty parameters. The most common one, and the most obvious, is this one:

```javascript
const fn = () => {
  // ...
}
```

However, some people don't seem to like having that empty set of parentheses there, so they made up this one here:

```javascript
const fn = _ => {
  // ...
}
```

(The reason for using the underscore is that linters won't complain about it being unused in the function body, in case you weren't aware.)

In my opinion, while it's more concise, the latter looks kind of ridiculous. It looks better when the function is passed as a parameter, I guess:

```javascript
doInBackground(_ => {
  // ...
});
```

Versus:

```javascript
doInBackground(() => {
  // ...
});
```

What do you guys think? I'm leaning towards the empty parentheses, both because I feel like it reads better and because it feels more correct since the underscore technically makes the function take an argument that it just doesn't use. But I'll leave it up for discussion.

**Comment by timkurvers** [comment]
What does our linter config do with this currently?

**Comment by sindrenm** [comment]
Without having tried it, I guess both would be allowed.
