### ISSUE TITLE
File Structure: Component Base Architecture or Angular Type Architecture?

### ISSUE THREAD

**Issue by fespinoza** [hyperoslo/javascript-playbook#2]

**Comment by sindrenm** [comment]
I think this ties into how we solve #3. Unless I'm misunderstanding this issue. :smiley:

**Comment by fespinoza** [comment]
I needed to elaborate more on this...

it is about file structure, do we keep stuff like

```
app/
|- directives/
  |- my_directive1.js
|- services/
  |- my_service1.js
```

or grouped by features

```
app/
|- components/
  |- feed/
    |- feed_service.js
    |- feed_directive.js
    |- feed.html
```

it does relate to the #3 as well

I want to try more the second approach

**Comment by sindrenm** [comment]
Right? And that ties into how we split up our application into modules. If we're to split it up into separate modules for each **area** of the app, then the latter makes sense. If we're to not split it up or create modules for each **type**, then the first setup makes sense. I'm leaning toward the component setup, like you. :smiley:

**Comment by fespinoza** [comment]
I think it's kind of the same idea of using rails engines

it's good that we are getting an agreement on this

my plan is doing a little project on angular from scratch, applying all this agreements as an example

and redact this resolutions in a guideline document, but first I want us to agree on the "Best Practices"

what do you guys think? @timkurvers @mathiasbno @JozoSalt ?

**Comment by sindrenm** [comment]
That sounds like a great idea, @fespinoza! :+1:

**Comment by fespinoza** [comment]
well I am starting sketching ideas of an example of an app using the json form for angular https://github.com/hyperoslo/hyp-json-form-angular
