### ISSUE TITLE
Usage of angular modules

### ISSUE THREAD

**Issue by fespinoza** [hyperoslo/javascript-playbook#3]

**Comment by sindrenm** [comment]
There are a few practices around this. Personally, I like the idea of splitting your application up into multiple modules based on what area of the app they belong to.

For instance, a blog could have the following modules:
1. `angular.module("blog", ["blog.categories", "blog.articles", "blog.users"])`
2. `angular.module("blog.categories", [])`
3. `angular.module("blog.articles", ["blog.categories"])`
4. `angular.module("blog.users”, [])`
5. …

The other common practice is to split on component type. For instance:
1. `angular.module("blog", ["blog.controllers", "blog.directives", "blog.filters", ...])`
2. `angular.module("blog.controllers", []);`
3. `angular.module("blog.directives", []);`
4. `angular.module("filters", []);`
5. …

And of course, there's the third way (which is probably way too normal) and that is not splitting it up at all. :wink:

**Comment by fespinoza** [comment]
I vote for the first approach, since I think then it's way easier to extract stuff as plugins

**Comment by sindrenm** [comment]
I agree. :smiley:

**Comment by fespinoza** [comment]
anyone else? in order to close the issue? @mathiasbno @timkurvers @JozoSalt

**Comment by JozoSalt** [comment]
I like the first approach :)

**Comment by timkurvers** [comment]
By module instead of type :+1:

**Comment by fespinoza** [comment]
agreed, then :)

**Comment by sindrenm** [comment]
Totally!

**Comment by sindrenm** [comment]
But I would still not close this issue quite yet, until we've got it documented in a PR. :smiley:

**Comment by fespinoza** [comment]
very well then
