### ISSUE TITLE
function/class definitions outside angular component declaration

### ISSUE THREAD

**Issue by fespinoza** [hyperoslo/javascript-playbook#4]

**Comment by sindrenm** [comment]
Do you mean whether to do this:

``` javascript
var BackwardsFilter = function () {
  return function (input) {
    var result = "";
    input = input || "";
    for (var i = 0; i < input.length; i++) {
      result = input.charAt(i) + result;
    }
    return result;
  };
};

angular.module("my-module").filter("backwards", BackwardsFilter);
```

Or this:

``` javascript
angular.module("my-module").filter("backwards", function () {
  return function (input) {
    var result = "";
    input = input || "";
    for (var i = 0; i < input.length; i++) {
      result = input.charAt(i) + result;
    }
    return result;
  };
});
```

**Comment by fespinoza** [comment]
exactly, thanks sindre

I would go for your first example

**Comment by sindrenm** [comment]
What do you consider the benefit of doing that? If your JS is not wrapped in an immediately invoking function, this would leak variables into the global scope.

**Comment by fespinoza** [comment]
well, it depends

if that it's on a self invoking anonimous function, I think it's the default setting when creating coffeescript files.
- the intention was just to have less indentation on the code
- be more open maybe with the class/function definition, so you can test logic "outside" angular (potentially)

**Comment by sindrenm** [comment]
Yeah, CoffeeScript does that for you. And having less indentation is kinda nice.
