### ISSUE TITLE
component directives with isolated scope

### ISSUE THREAD

**Issue by fespinoza** [hyperoslo/javascript-playbook#6]

**Comment by sindrenm** [comment]
What is this issue about? Whether or not to use isolated scopes on component directives?

**Comment by fespinoza** [comment]
yes... when you define a directive that it's supposed to be a component

I guess a rule of thumb is always to make the directive use Isolate scope

to be more modular and have this vision that components you can plug in/off

and this "components" should be restricted to "E" i think

**Comment by sindrenm** [comment]
Yeah, I think isolating the scope makes sense if you're creating re-usable component directives. Preventing the parent scope to leak into the directive's scope removes potential bugs that might occur if you have the parent scope available. If you need input for the directive, then pass them in as attributes to your directive explicitly instead. :+1:

**Comment by fespinoza** [comment]
exactly, so it's just to state this as a norm for component directives

**Comment by sindrenm** [comment]
Great! :smiley:
