### ISSUE TITLE
Controllers for directive logic?

### ISSUE THREAD

**Issue by fespinoza** [hyperoslo/javascript-playbook#7]

**Comment by sindrenm** [comment]
What do you mean? Whether or not to put directive logic in a `link` function or `controller` function? I generally prefer putting directive-specific logic into the controller function of the directive. There are some benefits to this. From the top of my head, I can think of two relatively good benefits:
1. If your directive is `require`d by another directive, then the controller for your directive will be injected into the other directive's linking function (fourth argument). Unless, of course, that directive has it's own controller function, in which case inheritance would take place. This is really great in terms of sharing values to child directives.
2. The controller function allows for dependency injection, which lets you inject services and the like for use only in that controller function. Of course, it would be possible to inject those dependencies when declaring the directive itself, but this is probably a cleaner way to do it.

However, there are probably different scenarios as to when one should use one or the other. And of course, there is also the `compile` function, and you might split the linking function into two parts as well: pre-link and post-link.

**Comment by fespinoza** [comment]
yeah, my question was regarding you are saying

and it's also because I found myself having really long directives, with a lot of logic on the link function, so I wasn't sure the best way to extract stuff there

Can you potentially reference a controller in an external file? I like the idea of testing some of the directive logic in its own controller, on its own file

I like your point of sharing logic between directives

so I guess a lot of stuff should go on the controller, instead of link, with the exception of specific visual stuff

**Comment by sindrenm** [comment]
Yeah, I'd leave DOM manipulation in the linking function(s) and other logic in the directive controller. :smiley:
