### ISSUE TITLE
Angular project embedded in Rails or Outside rails?

### ISSUE THREAD

**Issue by fespinoza** [hyperoslo/javascript-playbook#9]

**Comment by sindrenm** [comment]
That's the question, isn't it? At least in the scenario where you have multiple clients (like mobile apps as well as a web front-end), you would need to set up an API anyway. In that case, I think it makes sense to separate the web front-end code (the Angular code in this case) to a separate project. And that is certainly a lot cleaner than mixing the Angular into a Rails app, as well, which can be tricky at times. On the other hand, this would probably slow down development a bit, as you would need to boot up two servers and stuff and configure what URL the API is located at (probably best through an environment variable), but this shouldn't really take that much time, I think.

Generally, I love the idea of separating the front-end code from the back-end code as much as possible, and you would need an API in the back-end anyway, so I'm leaning more towards that one.

**Comment by fespinoza** [comment]
yeah I think the same... for me it's quite uggly to have a whole project structure under `app/assets/javascript`

and:
- if you decide to drop the client in the future and re-implement with let's say ember, it's possible without touching the backend
- I personally prefer testing tools specifically designed for javascript and angular, and not the adaptation gems to made them work with rails
- you don't leave space for developers to mix rails and angular code (as in setting values on erb files for angular)

in general I think is a way better practice in almost every scenario... it's not free (when you have one api and one client) but I think the benefits made the separation worth it

**Comment by sindrenm** [comment]
Agreed. :+1:

**Comment by JozoSalt** [comment]
Mixing a angular app and rails app can get really messy. And often you will be wasting time making custom hacks for things that just should work. I am all for keeping angular outside of rails.

**Comment by sindrenm** [comment]
Good. :grinning:
